# Generated by Django 5.2.1 on 2025-07-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grabacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_audio', models.FileField(upload_to='grabaciones/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('repeticiones', models.IntegerField(default=1)),
                ('duracion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField()),
                ('total_repeticiones', models.IntegerField()),
                ('tiempo_total', models.FloatField()),
                ('link_reporte', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
